server:
  port: 8099
spring:
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&useSSL=true